services:
  - type: web
    name: ai-for-her
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
